#!/bin/bash

# Exit immediately if a command exits with a non-zero status
set -e  

### Inform user and copy the ".vscode" directory into parent directory ###
echo
# Get setup directory and parent directory names
DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
PARENT="${DIR%/*}"
# Inform user
echo "Copying .vscode directory to $PARENT."
# Move .vscode if it exists
if [ -d "$DIR/.vscode" ]; then
    cp -rf "$DIR/.vscode" "$PARENT"
else
    echo "Warning: .vscode directory does not exist in $DIR."
fi

### Inform user and remove vsFoamAppCode directory ###
echo
# Inform user
read -p "Do you want to remove the vsFoamAppCode directory? (Y/n): " input
# Confirm before deletion
if [[ "$input" == "n" ]]; then
    echo "Skipping removal of $DIR."
else
    echo "Removing $DIR."
    rm -rf "$DIR"
fi

### Finalize user information ###
echo
# Inform user
echo "vsFoamAppCode installation was succesful, don't forget to load the desired openfoam environment before opening the solver files in vscode."
echo